"""Adding nationality and target info
Revision ID: 294f1652fbb3
Revises: 84bb6b8d24b2
Create Date: 2021-10-09 20:42:41.953045
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '294f1652fbb3'
down_revision = '84bb6b8d24b2'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_sub_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('terror_act', sa.BigInteger(), nullable=True),
    sa.Column('target_type', sa.Integer(), nullable=True),
    sa.Column('target_subtype', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('nationality', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nationality'], ['nationality.id'], ),
    sa.ForeignKeyConstraint(['target_subtype'], ['target_sub_type.id'], ),
    sa.ForeignKeyConstraint(['target_type'], ['target_type.id'], ),
    sa.ForeignKeyConstraint(['terror_act'], ['terrorist_act.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('terrorist_act', sa.Column('motive', sa.String(length=512), nullable=True))
    op.add_column('terrorist_act', sa.Column('success', sa.Boolean(), nullable=True))
    op.add_column('terrorist_act', sa.Column('suicide', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terrorist_act', 'suicide')
    op.drop_column('terrorist_act', 'success')
    op.drop_column('terrorist_act', 'motive')
    op.drop_table('target_info')
    op.drop_table('target_type')
    op.drop_table('target_sub_type')
    op.drop_table('nationality')
    # ### end Alembic commands ###