"""Weapon Info
Revision ID: 47e613bcadac
Revises: 294f1652fbb3
Create Date: 2021-10-09 22:38:38.674710
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '47e613bcadac'
down_revision = '294f1652fbb3'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_damage_extent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapon_subtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapon_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapon_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('terror_act', sa.BigInteger(), nullable=True),
    sa.Column('weapon_type', sa.Integer(), nullable=True),
    sa.Column('weapon_subtype', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['terror_act'], ['terrorist_act.id'], ),
    sa.ForeignKeyConstraint(['weapon_subtype'], ['weapon_subtype.id'], ),
    sa.ForeignKeyConstraint(['weapon_type'], ['weapon_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('terrorist_act', sa.Column('hostages', sa.Boolean(), nullable=True))
    op.add_column('terrorist_act', sa.Column('num_hostages', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('num_hostages_us', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('prop_comment', sa.String(length=1024), nullable=True))
    op.add_column('terrorist_act', sa.Column('prop_dam', sa.Boolean(), nullable=True))
    op.add_column('terrorist_act', sa.Column('prop_dam_ext', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('prop_dam_value', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('ransom', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('ransom_amt', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'terrorist_act', 'property_damage_extent', ['prop_dam_ext'], ['id'])
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terrorist_act', type_='foreignkey')
    op.drop_column('terrorist_act', 'weapon_detail')
    op.drop_column('terrorist_act', 'ransom_amt')
    op.drop_column('terrorist_act', 'ransom')
    op.drop_column('terrorist_act', 'prop_dam_value')
    op.drop_column('terrorist_act', 'prop_dam_ext')
    op.drop_column('terrorist_act', 'prop_dam')
    op.drop_column('terrorist_act', 'prop_comment')
    op.drop_column('terrorist_act', 'num_hostages_us')
    op.drop_column('terrorist_act', 'num_hostages')
    op.drop_column('terrorist_act', 'hostages')
    op.drop_column('terrorist_act', 'additional_notes')
    op.drop_table('weapon_info')
    op.drop_table('weapon_type')
    op.drop_table('weapon_subtype')
    op.drop_table('property_damage_extent')
    # ### end Alembic commands ###