"""Adding attack type
Revision ID: 7592af08f50c
Revises: 47e613bcadac
Create Date: 2021-10-10 00:43:51.358554
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '7592af08f50c'
down_revision = '47e613bcadac'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('act_to_attack_type',
    sa.Column('terror_act', sa.BigInteger(), nullable=True),
    sa.Column('attack_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attack_type'], ['attack_type.id'], ),
    sa.ForeignKeyConstraint(['terror_act'], ['terrorist_act.id'], )
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('act_to_attack_type')
    # ### end Alembic commands ###