"""Causualities
Revision ID: 84bb6b8d24b2
Revises: 6d19acd4724e
Create Date: 2021-10-09 19:04:33.948682
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '84bb6b8d24b2'
down_revision = '6d19acd4724e'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alt_designation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attack_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('terrorist_act', sa.Column('alt_designation', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('doubt_terrorism', sa.Boolean(), nullable=True))
    op.add_column('terrorist_act', sa.Column('num_injured', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('num_injured_us', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('num_killed', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('num_killed_us', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('num_perp_killed', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('num_perp_wounded', sa.Integer(), nullable=True))
    op.add_column('terrorist_act', sa.Column('part_of_multiple', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'terrorist_act', 'alt_designation', ['alt_designation'], ['id'])
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terrorist_act', type_='foreignkey')
    op.drop_column('terrorist_act', 'part_of_multiple')
    op.drop_column('terrorist_act', 'num_perp_wounded')
    op.drop_column('terrorist_act', 'num_perp_killed')
    op.drop_column('terrorist_act', 'num_killed_us')
    op.drop_column('terrorist_act', 'num_killed')
    op.drop_column('terrorist_act', 'num_injured_us')
    op.drop_column('terrorist_act', 'num_injured')
    op.drop_column('terrorist_act', 'doubt_terrorism')
    op.drop_column('terrorist_act', 'alt_designation')
    op.drop_table('attack_type')
    op.drop_table('alt_designation')
    # ### end Alembic commands ###