"""Bigger int
Revision ID: a411cc2739a3
Revises: 7592af08f50c
Create Date: 2021-10-10 02:16:29.037984
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = 'a411cc2739a3'
down_revision = '7592af08f50c'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terrorist_act', 'prop_dam_value',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terrorist_act', 'prop_dam_value',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###